### PR TITLE
Introduce the ability to alter the time reference used for TTL comparisons

### PR DESCRIPTION
**Pull request by zegelin**
I'm using this project with great success to extract data from Cassandra backups stored on S3.

I did have to make one small code change to the project. The majority of the data in the backups is written with TTLs. By the time I get around to processing these backups the data has partially or completely expired. The code change is to allow overriding the `nowInSec` value used by `CompactionStreamScanner`, which is the reference value used to test TTLs for expiry.

This feature can be used like so:

```
// set time reference for TTL comparison to "the beginning of time".
CompactionStreamScanner.setNowInSecSupplier(() -> 0); 
```

The change is honestly a bit of a hack. Happy to discuss if this approach is reasonable, or if there is a better way to add this functionality.

Notably, as multiple instances of `CompactionStreamScanner` will be used across the cluster, I have to call this within my `DataLayer` subclass' `readObject` method to ensure that every `CompactionStreamScanner` has the time reference adjusted. Not super ideal.

### CODE REVIEW

**Comment by jberragan** [comment]
Hi Adam, great news! Happy to hear this project is providing benefit. Can I suggest an alternative way, slightly more verbose but should allow users to override with their own time in the DataLayer: https://github.com/jberragan/spark-cassandra-bulkreader/pull/4

**Comment by jberragan** [comment]
Hi Adam, great news! Happy to hear this project is providing benefit. Can I suggest an alternative way, slightly more verbose but should allow user's to override with their own time in the DataLayer:

```suggestion
diff --git a/core/src/main/java/org/apache/cassandra/spark/data/DataLayer.java b/core/src/main/java/org/apache/cassandra/spark/data/DataLayer.java
index 8b6cd1c..5975eb2 100644
--- a/core/src/main/java/org/apache/cassandra/spark/data/DataLayer.java
+++ b/core/src/main/java/org/apache/cassandra/spark/data/DataLayer.java
@@ -27,6 +27,7 @@ import org.apache.cassandra.spark.stats.Stats;
 
 import org.apache.commons.lang.StringUtils;
 
+import org.apache.cassandra.spark.utils.TimeProvider;
 import org.apache.spark.sql.sources.EqualTo;
 import org.apache.spark.sql.sources.Filter;
 import org.apache.spark.sql.sources.In;
@@ -241,7 +242,17 @@ public abstract class DataLayer implements Serializable
         {
             return EmptyScanner.INSTANCE;
         }
-        return bridge().getCompactionScanner(cqlSchema(), partitioner(), sstables(filtersInRange), filtersInRange, columnFilter, readIndexOffset(), useIncrementalRepair(), stats());
+        return bridge().getCompactionScanner(cqlSchema(), partitioner(), sstables(filtersInRange),
+                                             filtersInRange, columnFilter, timeProvider(),
+                                             readIndexOffset(), useIncrementalRepair(), stats());
+    }
+
+    /**
+     * @return a TimeProvider that returns the time now in seconds. User can override with their own provider.
+     */
+    public TimeProvider timeProvider()
+    {
+        return bridge().timeProvider();
     }
 
     /**
diff --git a/core/src/main/java/org/apache/cassandra/spark/reader/CassandraBridge.java b/core/src/main/java/org/apache/cassandra/spark/reader/CassandraBridge.java
index bc93eee..a330507 100644
--- a/core/src/main/java/org/apache/cassandra/spark/reader/CassandraBridge.java
+++ b/core/src/main/java/org/apache/cassandra/spark/reader/CassandraBridge.java
@@ -32,6 +32,7 @@ import org.apache.cassandra.spark.reader.fourzero.FourZero;
 import org.apache.cassandra.spark.sparksql.filters.CustomFilter;
 import org.apache.cassandra.spark.sparksql.filters.PruneColumnFilter;
 import org.apache.cassandra.spark.stats.Stats;
+import org.apache.cassandra.spark.utils.TimeProvider;
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
@@ -138,12 +139,15 @@ public abstract class CassandraBridge
                                                                  @NotNull final Partitioner partitioner,
                                                                  @NotNull final String key);
 
+    public abstract TimeProvider timeProvider();
+
     // Compaction Stream Scanner
     public abstract IStreamScanner getCompactionScanner(@NotNull final CqlSchema schema,
                                                         @NotNull final Partitioner partitionerType,
                                                         @NotNull final SSTablesSupplier ssTables,
                                                         @NotNull final List<CustomFilter> filters,
                                                         @Nullable final PruneColumnFilter columnFilter,
+                                                        @NotNull final TimeProvider timeProvider,
                                                         final boolean readIndexOffset,
                                                         final boolean useIncrementalRepair,
                                                         @NotNull final Stats stats);
diff --git a/core/src/main/java/org/apache/cassandra/spark/reader/fourzero/CompactionStreamScanner.java b/core/src/main/java/org/apache/cassandra/spark/reader/fourzero/CompactionStreamScanner.java
index db92ccf..118c75f 100644
--- a/core/src/main/java/org/apache/cassandra/spark/reader/fourzero/CompactionStreamScanner.java
+++ b/core/src/main/java/org/apache/cassandra/spark/reader/fourzero/CompactionStreamScanner.java
@@ -6,6 +6,7 @@ import java.util.function.LongPredicate;
 import java.util.stream.Collectors;
 
 import org.apache.cassandra.spark.shaded.fourzero.cassandra.db.AbstractCompactionController;
+
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
@@ -19,7 +20,7 @@ import org.apache.cassandra.spark.shaded.fourzero.cassandra.db.compaction.Operat
 import org.apache.cassandra.spark.shaded.fourzero.cassandra.db.partitions.UnfilteredPartitionIterator;
 import org.apache.cassandra.spark.shaded.fourzero.cassandra.schema.CompactionParams;
 import org.apache.cassandra.spark.shaded.fourzero.cassandra.schema.TableMetadata;
-import org.apache.cassandra.spark.shaded.fourzero.cassandra.utils.FBUtilities;
+import org.apache.cassandra.spark.utils.TimeProvider;
 import org.jetbrains.annotations.NotNull;
 
 /*
@@ -51,13 +52,23 @@ public class CompactionStreamScanner extends AbstractStreamScanner
 
     private PurgingCompactionController controller;
     private AbstractCompactionStrategy.ScannerList scanners;
+    private final TimeProvider timeProvider;
     private CompactionIterator ci;
 
     CompactionStreamScanner(@NotNull final TableMetadata cfMetaData,
                             @NotNull final Partitioner partitionerType,
                             @NotNull final Set<FourZeroSSTableReader> toCompact)
+    {
+        this(cfMetaData, partitionerType, TimeProvider.INSTANCE, toCompact);
+    }
+
+    CompactionStreamScanner(@NotNull final TableMetadata cfMetaData,
+                            @NotNull final Partitioner partitionerType,
+                            @NotNull final TimeProvider timeProvider,
+                            @NotNull final Set<FourZeroSSTableReader> toCompact)
     {
         super(cfMetaData, partitionerType);
+        this.timeProvider = timeProvider;
         this.toCompact = toCompact;
         this.taskId = UUID.randomUUID();
     }
@@ -98,7 +109,7 @@ public class CompactionStreamScanner extends AbstractStreamScanner
     @Override
     UnfilteredPartitionIterator initializePartitions()
     {
-        final int nowInSec = FBUtilities.nowInSeconds();
+        final int nowInSec = timeProvider.now();
         final Keyspace keyspace = Keyspace.openWithoutSSTables(metadata.keyspace);
         final ColumnFamilyStore cfStore = keyspace.getColumnFamilyStore(metadata.name);
         this.controller = new PurgingCompactionController(cfStore, CompactionParams.TombstoneOption.NONE);
diff --git a/core/src/main/java/org/apache/cassandra/spark/reader/fourzero/FourZero.java b/core/src/main/java/org/apache/cassandra/spark/reader/fourzero/FourZero.java
index 0413259..4bd61e4 100644
--- a/core/src/main/java/org/apache/cassandra/spark/reader/fourzero/FourZero.java
+++ b/core/src/main/java/org/apache/cassandra/spark/reader/fourzero/FourZero.java
@@ -64,10 +64,12 @@ import org.apache.cassandra.spark.shaded.fourzero.cassandra.dht.RandomPartitione
 import org.apache.cassandra.spark.shaded.fourzero.cassandra.io.sstable.CQLSSTableWriter;
 import org.apache.cassandra.spark.shaded.fourzero.cassandra.locator.SimpleSnitch;
 import org.apache.cassandra.spark.shaded.fourzero.cassandra.schema.TableMetadata;
+import org.apache.cassandra.spark.shaded.fourzero.cassandra.utils.FBUtilities;
 import org.apache.cassandra.spark.shaded.fourzero.cassandra.utils.UUIDGen;
 import org.apache.cassandra.spark.sparksql.filters.CustomFilter;
 import org.apache.cassandra.spark.sparksql.filters.PruneColumnFilter;
 import org.apache.cassandra.spark.stats.Stats;
+import org.apache.cassandra.spark.utils.TimeProvider;
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
@@ -160,12 +162,19 @@ public class FourZero extends CassandraBridge
         return Pair.of(partitionKey, partitionKeyTokenValue);
     }
 
+    @Override
+    public TimeProvider timeProvider()
+    {
+        return FBUtilities::nowInSeconds;
+    }
+
     @Override
     public IStreamScanner getCompactionScanner(@NotNull final CqlSchema schema,
                                                @NotNull final Partitioner partitioner,
                                                @NotNull final SSTablesSupplier ssTables,
                                                @NotNull final List<CustomFilter> filters,
                                                @Nullable final PruneColumnFilter columnFilter,
+                                               @NotNull final TimeProvider timeProvider,
                                                final boolean readIndexOffset,
                                                final boolean useIncrementalRepair,
                                                @NotNull final Stats stats)
@@ -173,7 +182,7 @@ public class FourZero extends CassandraBridge
         //NOTE: need to use SchemaBuilder to init keyspace if not already set in C* Schema instance
         final FourZeroSchemaBuilder schemaBuilder = new FourZeroSchemaBuilder(schema, partitioner);
         final TableMetadata metadata = schemaBuilder.tableMetaData();
-        return new CompactionStreamScanner(metadata, partitioner, ssTables.openAll(
+        return new CompactionStreamScanner(metadata, partitioner, timeProvider, ssTables.openAll(
         ((ssTable, isRepairPrimary) -> FourZeroSSTableReader.builder(metadata, ssTable)
                                          .withFilters(filters)
                                          .withColumnFilter(columnFilter)
```

**Comment by jberragan** [comment]
Any comments on https://github.com/jberragan/spark-cassandra-bulkreader/pull/4? Can I merge in if it works for you?

**Comment by zegelin** [comment]
@jberragan #4 looks great, much cleaner than my approach. Thanks!

**Pull request closed without merging**
